slovo=input()
print (slovo[2], end="")
print (slovo[6], end="")
print (slovo[10])
print (slovo[0], end="")
print (slovo[-2], end="")
print (slovo [-1],)
print (slovo[:7])
print (slovo[4:])
print (slovo[1: None : 2])
print (len(slovo[1: None : 2]))
print (slovo[::-1])